export const ROUTES = {
    HOME: '/',
    SEARCH: '/search',
    JOURNALS: '/journals',
    JOURNAL: (slug: string) => `/journal/${slug}`,
    JOURNAL_ISSUES: (slug: string) => `/journal/${slug}/issues`,
    JOURNAL_EDITORS: (slug: string) => `/journal/${slug}/editors`,
    JOURNAL_ABOUT: (slug: string) => `/journal/${slug}/about`,
    JOURNAL_SUBMIT: (slug: string) => `/journal/${slug}/submission-guidelines`,
    JOURNAL_OA: (slug: string) => `/journal/${slug}/open-access`,
    ARTICLE: (doi: string) => `/article/${encodeURIComponent(doi)}`,
    BOOK: (isbn: string) => `/book/${isbn}`,
    CHAPTER: (doi: string) => `/chapter/${encodeURIComponent(doi)}`,
    AUTHOR: (authorId: string) => `/author/${authorId}`,
    DISCIPLINE: (subject: string) => `/subject/${subject}`,
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    ACCOUNT: '/account',
    ABOUT: '/about',
    PRIVACY: '/privacy-policy',
    TERMS: '/terms',
} as const;
